### ISSUE TITLE
Meaning of certain item identifiers

### ISSUE THREAD

**Issue by fernandobperezm** [finn-no/recsys_slates_dataset#17]
Hi!

First, thanks for an amazing contribution.

I've been using this dataset for my research activities recently and upon inspecting the impressions logs, I found that certain item identifiers may have special meaning. In particular, I'm assuming the following in my work.

* `0` is a filler value for when the user has no items in their slate or the slate is incomplete. A slate of size 20 will be filled with 0 up until position 25.
* `1` means a no-click, i.e., the user did not click any item present in the slate (This was described like this in this [paper](https://dl.acm.org/doi/10.1145/3460231.3474607).
* `2` fills in between items in the slate? For this particular one I don't have assumption, but I do see several repetitions of this item between slates and intra slate. If its not a filler, then can I assume that this is a highly popular item? If so, no user in the dataset interacted with it?

If possible, could you please validate if these assumptions are correct or not? Are there any other identifiers that I should be aware of? I'm attaching screenshots of some rows of the dataset for reference.
<img width="702" alt="Schermata 2022-02-25 alle 11 01 02" src="https://user-images.githubusercontent.com/10052938/155731705-f74f1698-2d95-4655-b8b7-cb113339259a.png">
<img width="656" alt="Schermata 2022-02-25 alle 11 03 23" src="https://user-images.githubusercontent.com/10052938/155731714-a4a1dfbc-b1e6-473d-b7cb-1e09a958143a.png">

**Comment by simeneide** [comment]
Hi @fernandobperezm, I am very happy that the dataset is useful for you. You are correct in your assumptions. Item 2 is an UNK item, which implies that there was an actual item there, but we dont have the ID in the dataset. There are a couple of cases this can happen for example if the item was deleted from the platform at the point of data collection.

```
0 : PAD
1 : Noclick
2 : UNK
```

This is described in the quickstart-notebook ( http://opensource.finn.no/recsys_slates_dataset/#quickstart-dataset) but if you found it unclear, maybe we should emphasis it more somewhere.

**Comment by simeneide** [comment]
@fernandobperezm did I answer your questions, and if so, can I close the issue? :)

**Comment by fernandobperezm** [comment]
Oh! Sorry! yes, your reply was awesome! Thank you very much.

I did not receive a notification of the latest reply 🧐 but in any case I'm closing the issue as my doubt was resolved.

Thanks again!
