### ISSUE TITLE
Linked website redirects to another page 

### ISSUE THREAD

**Issue by fernandobperezm** [finn-no/recsys_slates_dataset#24]
Hi!

I noticed that the link [http://opensource.finn.no/recsys_slates_dataset/](http://opensource.finn.no/recsys_slates_dataset/) is now redirecting to [https://opensource.finntech.no](https://opensource.finntech.no). 

I remember in the past, this link held a GitHub page (or similar) with information on the dataset. Is this change expected? 

Bests!

**Comment by simeneide** [comment]
Yeah, it should redirect to a documentation page. I checked internally, and there were some security vulnerability stuff with the setup so they removed it. Will need to check up on that.

however, if you look at the `.ipynb` files in the repo, all the documentation should be there on the various helper packages :) (see e.g. https://github.com/finn-no/recsys_slates_dataset/blob/main/dataset_torch.ipynb)

**Comment by fernandobperezm** [comment]
Alright! I'll check out those Jupyter notebooks 👍 

Thanks!
